### PR TITLE
[frontend] initial styling

### PR DESCRIPTION
**Pull request by adirar111**
this PR adds styling!

the booking page is not styled yet, to be tackled in a different PR

@Tricia-Faith-Cu and i were thinking of doing more clean up/ tidying/ using css-vars in a later PR

Screen Shot 2022-03-19 at 11 56 01 AM
Screen Shot 2022-03-19 at 11 56 03 AM
Screen Shot 2022-03-19 at 11 56 06 AM

### CODE REVIEW

**Review by wrenliang — APPROVED** [review]
This is awesome, thank you @adirar111 and @Tricia-Faith-Cu !!!

@adirar111 I resolved the conflicts from @mhanray and @ryan-kanghyun-moon's changes into this branch, please double-check `const handleMergeAvailabilities = React.useCallback` (BookingPage.tsx, line 46) is working properly! Otherwise good to go

**Review by Tricia-Faith-Cu — CHANGES_REQUESTED** [review]
Should we remove the JSON body in page 2 before we forget? The { 'event' : 'not created yet' }

**Comment by adirar111** [comment]
thanks for flagging @Tricia-Faith-Cu !

tested the full flow and realized there was a routing bug which should hopefully be fixed now

Screen Shot 2022-03-24 at 5 43 48 PM

**Review by Tricia-Faith-Cu — APPROVED** [review]

**Comment by Tricia-Faith-Cu** [comment]
Thanks for fixing the bug! looks good to me

**Pull request merged**
